name: Daily Flight Scrape

on:
  schedule:
    - cron: '0 2 * * *'       # codziennie o 03:00 Europe/Warsaw (02:00 UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npx playwright install --with-deps

    - name: Init DB
      run: |
        python - << 'EOF'
        from db import init_db
        init_db()
        EOF

    - name: Run scraper
      env:
        PYTHONUNBUFFERED: "1"
      run: python -u runner.py


    - name: Upload flights.db
      uses: actions/upload-artifact@v4
      with:
        name: flights-db
        path: flights.db

# re-enable scheduled workflow
